### ISSUE TITLE
RetrieveNewOrdersExample.java 's authenitcation call is not compatible with the latest loginWithWixInstance()

### ISSUE THREAD

**Issue by ravithb** [wix/wix-restaurants-java-sdk#2]
The example shows 

`System.out.print("Authenticating...");
        final WixRestaurantsAuthenticationClient authentication = wixRestaurants.getAuthenticationClient();
        final String accessToken = authentication.loginWithWixInstance(wixInstance).accessToken;
        System.out.println(" done (accessToken: " + accessToken + ").");`

However the latest version accepts two parameters for the loginWithWixInstance method.

The example needs to be updated to reflect this method signature change.

**Comment by ravithb** [comment]
Seems like it requires to add the latest version of the authentication-api to the deps. Example seems correct when compared to the latest authentication-api method.

**Comment by dleshem** [comment]
Fixed in version 1.17.0 (just released).
